// Generated by flutterfire from google-services.json
// Project: jerry-4f2c5

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) throw UnsupportedError('Web not configured.');
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError('iOS not configured.');
      default:
        throw UnsupportedError('Unsupported platform.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey:            'AIzaSyAEfba33ia9LvCozD5FUW49gQ0myMOrIYw',
    appId:             '1:703344031887:android:3a315b73d3ff2a45d898fa',
    messagingSenderId: '703344031887',
    projectId:         'jerry-4f2c5',
    storageBucket:     'jerry-4f2c5.firebasestorage.app',
  );
}
